// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_j64LutDQqAxqlfK5HFWfjFPFSq-AQfA',
    appId: '1:386904868206:web:dc374d5bd32f8961cbed7f',
    messagingSenderId: '386904868206',
    projectId: 'instaappbasic',
    authDomain: 'instaappbasic.firebaseapp.com',
    storageBucket: 'instaappbasic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNVp4KShVrL7NVffrVVLcUFpXQVRuhH0',
    appId: '1:386904868206:android:5a3dd99e13c24141cbed7f',
    messagingSenderId: '386904868206',
    projectId: 'instaappbasic',
    storageBucket: 'instaappbasic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTEy7w74it51ajsZ8ipTWnyCIrBbOmSU',
    appId: '1:386904868206:ios:41c659269b44cb92cbed7f',
    messagingSenderId: '386904868206',
    projectId: 'instaappbasic',
    storageBucket: 'instaappbasic.appspot.com',
    iosBundleId: 'com.instagram.nk.instagram',
  );
}
